{% set name = "oclgrind" %}
{% set version = "21.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jrprice/Oclgrind/archive/v{{ version }}.tar.gz
  sha256: b40ea81fcf64e9012d63c3128640fde9785ef4f304f9f876f53496595b8e62cc

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}    # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - vs2017_{{ target_platform }}  # [win]
    - cmake
    - make    # [unix]
    - ninja   # [win]
  host:
    - llvmdev   >=6.0.0,<14
    - clangdev
    - readline  # [unix]
    - khronos-opencl-icd-loader  # [win]
    - zlib

test:
  commands:
    - test -f "$PREFIX/lib/liboclgrind-rt-icd${SHLIB_EXT}"         # [unix]
    - if not exist %LIBRARY_BIN%\\oclgrind-rt-icd.dll exit 1       # [win]
    - oclgrind --help

about:
  home: https://github.com/jrprice/Oclgrind
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'An OpenCL device simulator and debugger'
  dev_url: https://github.com/jrprice/Oclgrind
  doc_url: https://github.com/jrprice/Oclgrind/wiki/

extra:
  recipe-maintainers:
    - isuruf
    - matthiasdiener
