{% set name = "oclgrind" %}
{% set version = "32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jrprice/Oclgrind/archive/v{{ version }}.tar.gz
  sha256: 578ab3d510f86a2478e2f392e7a491eed31e90e3e4309e597f58f2c244cca45a

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}    # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - vs2017_{{ target_platform }}  # [win]
    - cmake
    - make    # [unix]
    - ninja   # [win]
  host:
    - llvmdev   >=6.0.0,<10.0.0.a0
    - clangdev
    - readline  # [unix]
    - khronos-opencl-icd-loader  # [win]

test:
  commands:
    - test -f "$PREFIX/lib/liboclgrind-rt-icd${SHLIB_EXT}"         # [unix]
    - if not exist %LIBRARY_BIN%\\oclgrind-rt-icd.dll exit 1       # [win]
    - oclgrind --help

about:
  home: https://github.com/jrprice/Oclgrind
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An OpenCL device simulator and debugger
  dev_url: https://github.com/jrprice/Oclgrind

extra:
  recipe-maintainers:
    - isuruf
