{% set name = "oclgrind" %}
{% set version = "19.10" %}
{% set llvm_version = "9.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jrprice/Oclgrind/archive/v{{ version }}.tar.gz
  sha256: f9a8f22cb9f6d88670f2578c46ba0d728ba8eaee5c481c2811129dc157c43dc0

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}    # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - vs2017_{{ target_platform }}  # [win]
    - cmake
    - ninja   # [win]
  host:
    - llvmdev   {{ llvm_version }}
    - clangdev  {{ llvm_version }}
    - llvm
    - readline  # [unix]

test:
  commands:
    - test -f "$PREFIX/lib/liboclgrind-rt-icd${SHLIB_EXT}"         # [unix]
    - if not exist %LIBRARY_BIN%\\oclgrind-rt-icd.dll exit 1       # [win]
    - oclgrind --help

about:
  home: https://github.com/jrprice/Oclgrind
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'An OpenCL device simulator and debugger'
  dev_url: https://github.com/jrprice/Oclgrind

extra:
  recipe-maintainers:
    - isuruf
