appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Lew0rCc6If4We2YwRCf0MUJrGuFDA6qN6R4JkWHEXLQCej9c04ikxnAhjHdT5UgdHX/u3QU/Qtwtwm95LjK1HymjDIAI2k2gmI2wj+GYnLwQOseasGeKA7dKmLK3KESQm5c730o0e+GDNTGOH7VNvVTYiLuWl6Nz9QIDiZwcqiwOquDCti/IJJI1TW+nfoC989WYO6TqjVqWFrLvD4MmXrkJr7J1mzPyi3520X87DbEtgQ7i4TBw0VcL6tJl058mbUAOxsSGsv/VlBTo0+OcAOl2S4f+awHkcwpJS273uXRPa5MIUi00DiBOXMDbKXQs2+HI/u269UscOl/xPwhvZC5tkYRpgU0OuNpDfpJoBNW1vRZFRixkOmL/j5dd65PYjOO+m8skwYqB27lcCyPaZTcIL0NLfBYoP1LOWMyI2eF4kIBQbspAV1UNSiuyC9y0mf9fhs2gowj8IzsIzPGYfrQxJRLkg/gVj119Rrx2Zgs9qFiqnwyHJWfuQ/Uk1whhf8IFP3/b7WprX+vcdzaaVSCm/swOiLiyNOAmQiUxjI7ghnM46BzlCzUdVXxdym8SJW+qJbXMRo808WsP6BWB98GI1HPp1Q2sT0gNBcIKJ91D2Ibab1AZ2zEzpiuN4Be5/D/WUovtqXUKF0QnsjTFGYvvdlMUe1W3E5siEEBgZac=}
